# NumPy

In this chapter, our focus will be on the following topics:
* Understanding NumPy arrays
* NumPy array numerical data types
* Manipulating array shapes
* The stacking of NumPy arrays
* Partitioning NumPy arrays
* Changing the data type of NumPy arrays
* Creating NumPy views and copies
* Slicing NumPy arrays
* Boolean and fancy indexing
* Broadcasting arrays
* Creating pandas DataFrames
* Understanding pandas Series
* Reading and querying the Quandl data
* Describing pandas DataFrames

NumPy arrays are a series of homogenous items. Homogenous means the
array will have all the elements of the same data type

In [1]:
import numpy as np
import pandas as pd

In [2]:
#create an array
array=np.array([2,3,4,5,6,8,7,6,5,4,3])
array

array([2, 3, 4, 5, 6, 8, 7, 6, 5, 4, 3])

Another way to create a NumPy array is with arange(). It creates an evenly spaced
NumPy array. Three values – start, stop, and step – can be passed to the
arange(start,[stop],step)

In [5]:
# Creating an array using arange()
range_array=np.arange(1,15)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Apart from the array() and arange() functions, there are other options, such as
zeros(), ones(), full(), eye(), and random(), which can also be used to create a
NumPy array, as these functions are initial placeholders. Here is a detailed description of
each function:
* zeros(): The zeros()function creates an array for a given dimension with all
zeroes.
* ones(): The ones() function creates an array for a given dimension with all
ones.
* fulls(): The full() function generates an array with constant values.
* eyes(): The eye() function creates an identity matrix.
* random(): The random() function creates an array with any given dimension.


In [7]:
# Create an array of all zeros
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# Create an array of all ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Create an array of constant
np.full((3,4),6)


array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [14]:
# Create a 2x2 identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [18]:
# Create an array filled with random values
np.random.random((3,3))


array([[0.70282223, 0.71441859, 0.27259016],
       [0.29708597, 0.40553644, 0.16826268],
       [0.56141256, 0.52982417, 0.84159499]])

# Array features

## Selecting array elements

In [21]:
arry=np.array([[1,2,3],[2,3,4]])
arry

array([[1, 2, 3],
       [2, 3, 4]])

e. We just need to specify the index of the matrix as
a[m,n]. Here, m is the row index and n is the column index of the matrix. \n
Array [Row] [Col]

In [26]:
arry[1]

array([2, 3, 4])

In [29]:
arry[1][2]

4

# Manipulating array shapes

In this section, our main focus is on array manipulation. Let's learn some new Python
functions of NumPy, such as 
* reshape()
* flatten() 
* ravel()
* transpose()
* resize():

#### reshape() will change the shape of the array:


In [34]:
d3=np.arange(4,13).reshape(3,3)
d3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

####  flatten() transforms an n-dimensional array into a one-dimensional array

In [35]:
d3.flatten()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

#### The ravel() function is similar to the flatten() function. It also transforms an
n-dimensional array into a one-dimensional array. The main difference is that
flatten() returns the actual array while ravel() returns the reference of the
original array. The ravel() function is faster than the flatten() function
because it does not occupy extra memory:


In [36]:
d3.ravel()

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

#### The transpose() function is a linear algebraic function that transposes the
given two-dimensional matrix.

In [38]:
print(d3)
d3.transpose()

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 4,  7, 10],
       [ 5,  8, 11],
       [ 6,  9, 12]])

In [46]:
np.resize(1,9)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

# The stacking of NumPy arrays
NumPy offers a stack of arrays. Stacking means joining the same dimensional arrays along
with a new axis. Stacking can be done horizontally, vertically, column-wise, row-wise, or
depth-wise:

In [52]:
ar1=np.arange(1,10).reshape(3,3)
ar1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
ar2=np.array([[11,12,13],[14,15,16],[17,18,19]])
ar2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### Horizontal stacking:
In horizontal stacking, the same dimensional arrays are
joined along with a horizontal axis using the hstack() and concatenate()
functions.

In [56]:
np.hstack((ar1, ar2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [59]:
#if we dont use axis 1 then it vertical stake
np.concatenate((ar1, ar2), axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

#### Vertical stacking:
In vertical stacking, the same dimensional arrays are joined
along with a vertical axis using the vstack() and concatenate() functions.
Let's see the following example:


In [60]:
np.vstack((ar1, ar2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [61]:
np.concatenate((ar1,ar2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

#### Depth stacking:
In depth stacking, the same dimensional arrays are joined along
with a third axis (depth) using the dstack() function. Let's see the following
example:

In [62]:
np.dstack((ar1, ar2))

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13]],

       [[ 4, 14],
        [ 5, 15],
        [ 6, 16]],

       [[ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

#### Column stacking:
Column stacking stacks multiple sequence one-dimensional
arrays as columns into a single two-dimensional array. Let's see an example of
column stacking

In [69]:
a1=np.arange(1,6)
a1

array([1, 2, 3, 4, 5])

In [66]:
a2=np.arange(6,11)
a2

array([ 6,  7,  8,  9, 10])

In [70]:
np.column_stack((a1,a2))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

#### Row stacking:
Row stacking stacks multiple sequence one-dimensional arrays as
rows into a single two-dimensional arrays. Let's see an example of row stacking:

In [71]:
np.row_stack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Partitioning NumPy arrays

NumPy arrays can be partitioned into multiple sub-arrays. NumPy offers three types of
split functionality: vertical, horizontal, and depth-wise. All the split functions by default
split into the same size arrays but we can also specify the split location. Let's look at each of
the functions in detail

#### Horizontal splitting:
In horizontal split, the given array is divided into N equal
sub-arrays along the horizontal axis using the hsplit() function. Let's see how
to split an array:

In [76]:
b=np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.hsplit(b,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [81]:
np.vsplit(b,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [84]:
np.split(b,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [85]:
np.split(b,3, axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]